### ISSUE TITLE
Support -f flag

### ISSUE THREAD

**Issue by RedBeard0531** [jhasse/ja#3]
I keep several .ninja files for different build options (static/dynamic, gcc/clang, etc). I can't use ja because it only supports the default build.ninja file. It seems like ja should just forward all options to ninja rather than trying to parse them so that you automatically support all ninja flags rather than having to add code for each one.

**Comment by jhasse** [comment]
> It seems like ja should just forward all options to ninja rather than trying to parse them so that you automatically support all ninja flags rather than having to add code for each one.

It does that actually for everything that doesn't start with `-` ;) ja is using [click](https://github.com/pallets/click) which checks all specified options. If there's a way to forward the options while still using click for the ones ja is interested in, that would be perfect. I don't know how to do that though :/

I've implemented the `-f` option, thanks for the report :)
